(function(root,factory){'use strict';const api=factory();if(typeof module!=='undefined'&&module.exports)module.exports=api;if(root)root.FitCoachCoachOpsV47=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const finite=(v,f=0)=>{if(v===''||v==null)return f;const n=Number(v);return Number.isFinite(n)?n:f};
const clamp=(v,a,b)=>Math.min(b,Math.max(a,finite(v)));
const daysSince=date=>{if(!date)return Infinity;const t=new Date(String(date).slice(0,10)+'T12:00:00').getTime();return Number.isFinite(t)?Math.max(0,(Date.now()-t)/86400000):Infinity};
function clientSignals(client={}){const c=(Array.isArray(client.checkins)?client.checkins:[]).at(-1)||{};const overdue=daysSince(c.date);const adherence=clamp(c.adherence??1,0,1),recovery=clamp(c.recovery??3,1,5),sleep=clamp(c.sleep??3,1,5),performance=clamp(c.performance??0,-1,1),hunger=clamp(c.hunger??3,1,5);return{overdue,adherence,recovery,sleep,performance,hunger,hasCheckin:Boolean(c.date)};}
function priority(client={}){const s=clientSignals(client);let score=0,reasons=[];if(!s.hasCheckin){score+=45;reasons.push('Sin check-in inicial');}else if(s.overdue>=10){score+=35;reasons.push('Check-in muy vencido');}else if(s.overdue>=7){score+=22;reasons.push('Check-in pendiente');}if(s.adherence<.6){score+=26;reasons.push('Adherencia baja');}else if(s.adherence<.75){score+=14;reasons.push('Adherencia mejorable');}if(s.recovery<=2){score+=20;reasons.push('Recuperación baja');}if(s.sleep<=2){score+=14;reasons.push('Sueño bajo');}if(s.performance<=-.5){score+=18;reasons.push('Rendimiento descendente');}if(s.hunger>=5){score+=8;reasons.push('Hambre alta');}score=Math.min(100,score);const level=score>=60?'critical':score>=35?'high':score>=15?'medium':'low';return{score,level,reasons,signals:s};}
function nextAction(client={}){const p=priority(client);if(!p.signals.hasCheckin)return{type:'checkin',label:'Completar primer check-in',priority:p};if(p.signals.overdue>=7)return{type:'checkin',label:'Solicitar check-in semanal',priority:p};if(p.signals.recovery<=2||p.signals.performance<=-.5)return{type:'review',label:'Revisar fatiga y entrenamiento',priority:p};if(p.signals.adherence<.75)return{type:'nutrition',label:'Revisar adherencia y fricción nutricional',priority:p};if((client.decisions||[]).length===0)return{type:'review',label:'Revisar primera propuesta',priority:p};return{type:'monitor',label:'Seguimiento normal',priority:p};}
function operationsBoard(clients=[]){return(Array.isArray(clients)?clients:[]).filter(c=>c?.status!=='paused').map(c=>({id:c.id,name:c.name||'Cliente',goal:c.goal||'recomp',...nextAction(c)})).sort((a,b)=>b.priority.score-a.priority.score||a.name.localeCompare(b.name));}
function applyTrainingDecision(plan={},decision={}){if(!plan||typeof plan!=='object')return plan;const modifier=clamp(decision.volumeModifier??1,.7,1.2),deload=Boolean(decision.deload);const routine=plan.routine&&typeof plan.routine==='object'?plan.routine:null;if(!routine)return{...plan,coachDecision:{...decision,appliedAt:new Date().toISOString()}};const next={};for(const [day,items] of Object.entries(routine)){next[day]=(Array.isArray(items)?items:[]).map(ex=>{const sets=Math.max(1,Math.round(finite(ex.sets,1)*(deload?Math.min(.7,modifier):modifier)));return{...ex,sets};});}return{...plan,routine:next,coachDecision:{volumeModifier:modifier,deload,appliedAt:new Date().toISOString()}};}
return{clientSignals,priority,nextAction,operationsBoard,applyTrainingDecision};});

if(typeof document!=='undefined')(()=>{'use strict';const KEY='fitcoach_clients_v40';const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};function render(){const sec=document.getElementById('clients');const api=globalThis.FitCoachCoachOpsV47;if(!sec||!api)return;let host=document.getElementById('cwOpsV47');if(!host){host=document.createElement('div');host.id='cwOpsV47';host.className='card';host.style.margin='12px 0';const h=sec.querySelector('h1');h?.after(host);}const board=api.operationsBoard(read());const urgent=board.filter(x=>x.priority.level==='critical'||x.priority.level==='high');host.innerHTML=`<h3>Cola operativa</h3><div class="muted">${urgent.length} clientes requieren atención prioritaria</div>${board.slice(0,8).map(x=>`<div style="display:flex;justify-content:space-between;gap:12px;align-items:center;padding:9px 0;border-bottom:1px solid #ffffff12"><div><strong>${String(x.name).replace(/[&<>"']/g,'')}</strong><div class="muted">${x.label}</div></div><div style="text-align:right"><strong>${x.priority.score}</strong><div class="muted">${x.priority.level}</div></div></div>`).join('')||'<div class="muted" style="margin-top:8px">Sin clientes todavía.</div>'}`;}
function boot(){render();document.addEventListener('fitcoach:clients-updated',render);setInterval(render,30000);}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot,{once:true}):boot();})();
