window.FITCOACH_DATA = {
  exercises: [
    {id:'bench_db',name:'Press banca con mancuernas',muscle:'Pecho',equipment:'Mancuernas',level:'Intermedio',pattern:'Empuje horizontal',alt:'Press en máquina',steps:['Apoya pies y escápulas.','Baja las mancuernas con control.','Empuja sin perder la posición.'],errors:['Abrir demasiado los codos.','Rebotar o acortar el recorrido.']},
    {id:'incline_db',name:'Press inclinado con mancuernas',muscle:'Pecho',equipment:'Mancuernas',level:'Intermedio',pattern:'Empuje inclinado',alt:'Press inclinado en máquina',steps:['Ajusta el banco a 20-35°.','Baja hacia la parte alta del pecho.','Empuja manteniendo hombros estables.'],errors:['Exceso de inclinación.','Encoger los hombros.']},
    {id:'cable_fly',name:'Aperturas en polea',muscle:'Pecho',equipment:'Polea',level:'Intermedio',pattern:'Aducción horizontal',alt:'Pec deck',steps:['Mantén codos semiflexionados.','Cierra los brazos sin perder tensión.','Regresa lentamente.'],errors:['Usar demasiado peso.','Convertirlo en un press.']},
    {id:'chest_row',name:'Remo con apoyo de pecho',muscle:'Espalda',equipment:'Mancuernas',level:'Principiante',pattern:'Tracción horizontal',alt:'Remo en máquina',steps:['Apoya el pecho.','Tira con los codos.','Controla la bajada.'],errors:['Encoger hombros.','Usar impulso.']},
    {id:'lat_pulldown',name:'Jalón al pecho',muscle:'Espalda',equipment:'Polea',level:'Principiante',pattern:'Tracción vertical',alt:'Dominada asistida',steps:['Inicia con depresión escapular.','Lleva la barra al pecho alto.','Sube con control.'],errors:['Tirar detrás de la nuca.','Balancear el tronco.']},
    {id:'seated_row',name:'Remo en polea',muscle:'Espalda',equipment:'Polea',level:'Principiante',pattern:'Tracción horizontal',alt:'Remo unilateral',steps:['Mantén torso estable.','Lleva codos hacia atrás.','Pausa brevemente.'],errors:['Balancear el tronco.','Acortar el recorrido.']},
    {id:'ohp',name:'Press militar sentado',muscle:'Hombros',equipment:'Mancuernas',level:'Intermedio',pattern:'Empuje vertical',alt:'Press de hombros en máquina',steps:['Activa abdomen.','Empuja en plano escapular.','Baja con control.'],errors:['Hiperextender la espalda.','Bajar demasiado.']},
    {id:'lateral_raise',name:'Elevaciones laterales',muscle:'Hombros',equipment:'Mancuernas',level:'Principiante',pattern:'Abducción',alt:'Elevación lateral en polea',steps:['Sube hasta la línea de hombros.','Mantén ligera flexión de codo.','Baja lentamente.'],errors:['Usar impulso.','Encoger trapecios.']},
    {id:'rear_delt',name:'Pájaros en máquina',muscle:'Hombros',equipment:'Máquina',level:'Principiante',pattern:'Abducción horizontal',alt:'Face pull',steps:['Apoya el pecho.','Abre con los codos.','Pausa atrás.'],errors:['Arquear la espalda.','Usar demasiado peso.']},
    {id:'ez_curl',name:'Curl con barra EZ',muscle:'Bíceps',equipment:'Barra',level:'Principiante',pattern:'Flexión de codo',alt:'Curl con mancuernas',steps:['Mantén codos fijos.','Flexiona sin balancear.','Baja completa.'],errors:['Mover los hombros.','Extender las muñecas.']},
    {id:'hammer_curl',name:'Curl martillo',muscle:'Bíceps',equipment:'Mancuernas',level:'Principiante',pattern:'Flexión neutra',alt:'Curl con cuerda',steps:['Muñeca neutra.','Codo estable.','Controla la bajada.'],errors:['Balanceo.','Recorrido corto.']},
    {id:'pushdown',name:'Extensión de tríceps en polea',muscle:'Tríceps',equipment:'Polea',level:'Principiante',pattern:'Extensión de codo',alt:'Fondos asistidos',steps:['Codos pegados.','Extiende completamente.','Regresa sin mover el hombro.'],errors:['Abrir codos.','Inclinarse demasiado.']},
    {id:'overhead_tri',name:'Tríceps por encima de la cabeza',muscle:'Tríceps',equipment:'Polea',level:'Intermedio',pattern:'Extensión de codo',alt:'Press francés',steps:['Codos al frente.','Estira sin arquear la espalda.','Extiende por completo.'],errors:['Abrir codos.','Mover el tronco.']},
    {id:'rdl',name:'Peso muerto rumano',muscle:'Isquios',equipment:'Barra',level:'Intermedio',pattern:'Bisagra de cadera',alt:'Curl femoral',steps:['Lleva la cadera atrás.','Mantén la barra cerca.','Sube contrayendo glúteos.'],errors:['Redondear la espalda.','Flexionar demasiado las rodillas.']},
    {id:'leg_press',name:'Prensa de piernas',muscle:'Cuádriceps',equipment:'Máquina',level:'Principiante',pattern:'Dominante de rodilla',alt:'Hack squat',steps:['Apoya espalda y pelvis.','Baja con rango tolerable.','Empuja sin bloquear agresivamente.'],errors:['Despegar la pelvis.','Bloquear rodillas.']},
    {id:'leg_extension',name:'Extensión de cuádriceps',muscle:'Cuádriceps',equipment:'Máquina',level:'Principiante',pattern:'Extensión de rodilla',alt:'Step-up bajo',steps:['Alinea el eje de la máquina.','Extiende y pausa.','Baja con control.'],errors:['Golpear los topes.','Carga excesiva.']},
    {id:'leg_curl',name:'Curl femoral sentado',muscle:'Isquios',equipment:'Máquina',level:'Principiante',pattern:'Flexión de rodilla',alt:'Curl femoral tumbado',steps:['Ajusta el respaldo.','Flexiona la rodilla.','Controla la vuelta.'],errors:['Levantar la cadera.','Rebotar.']},
    {id:'hip_thrust',name:'Hip thrust',muscle:'Glúteos',equipment:'Barra',level:'Intermedio',pattern:'Extensión de cadera',alt:'Puente de glúteo',steps:['Apoya la espalda alta.','Empuja con los pies.','Pausa arriba sin hiperextender.'],errors:['Arquear la espalda.','Pies demasiado lejos.']},
    {id:'reverse_lunge',name:'Zancada atrás',muscle:'Glúteos',equipment:'Mancuernas',level:'Intermedio',pattern:'Unilateral',alt:'Step-up',steps:['Da un paso atrás estable.','Baja con control.','Empuja con la pierna delantera.'],errors:['Paso demasiado corto.','Perder equilibrio.']},
    {id:'calf_raise',name:'Gemelo de pie',muscle:'Gemelos',equipment:'Máquina',level:'Principiante',pattern:'Flexión plantar',alt:'Gemelo en prensa',steps:['Baja hasta estirar.','Sube y pausa.','Mantén rodilla extendida.'],errors:['Rebotar.','Recorrido corto.']},
    {id:'cable_crunch',name:'Crunch en polea',muscle:'Core',equipment:'Polea',level:'Intermedio',pattern:'Flexión de tronco',alt:'Reverse crunch',steps:['Acerca costillas a pelvis.','Mantén cadera estable.','Sube lentamente.'],errors:['Tirar con los brazos.','Mover la cadera.']},
    {id:'dead_bug',name:'Dead bug',muscle:'Core',equipment:'Peso corporal',level:'Principiante',pattern:'Anti-extensión',alt:'Plancha',steps:['Pega lumbar al suelo.','Extiende brazo y pierna contraria.','Vuelve sin perder control.'],errors:['Arquear la espalda.','Mover demasiado rápido.']}
    ,{id:'goblet_squat',name:'Sentadilla goblet',muscle:'Cuádriceps',equipment:'Mancuerna',level:'Principiante',pattern:'Dominante de rodilla',alt:'Prensa de piernas',steps:['Sujeta la mancuerna frente al pecho.','Desciende manteniendo el tronco estable.','Empuja el suelo para subir.'],errors:['Colapsar las rodillas.','Perder la posición lumbar.']}
    ,{id:'one_arm_row',name:'Remo unilateral con mancuerna',muscle:'Espalda',equipment:'Mancuerna',level:'Principiante',pattern:'Tracción horizontal',alt:'Remo en polea',steps:['Apoya una mano y una rodilla.','Tira del codo hacia la cadera.','Baja de forma controlada.'],errors:['Rotar el tronco.','Encoger el hombro.']}
    ,{id:'cable_pullover',name:'Pullover en polea',muscle:'Espalda',equipment:'Polea',level:'Intermedio',pattern:'Extensión de hombro',alt:'Jalón al pecho',steps:['Inclina ligeramente el torso.','Lleva la barra hacia los muslos.','Mantén los codos casi extendidos.'],errors:['Convertirlo en un jalón.','Mover demasiado el tronco.']}
    ,{id:'machine_press',name:'Press en máquina',muscle:'Pecho',equipment:'Máquina',level:'Principiante',pattern:'Empuje horizontal',alt:'Press banca con mancuernas',steps:['Ajusta el asiento.','Empuja sin despegar la espalda.','Regresa con control.'],errors:['Bloquear agresivamente.','Acortar el recorrido.']}
    ,{id:'machine_incline',name:'Press inclinado en máquina',muscle:'Pecho',equipment:'Máquina',level:'Principiante',pattern:'Empuje inclinado',alt:'Press inclinado con mancuernas',steps:['Ajusta el asiento al pecho alto.','Empuja en línea estable.','Controla la vuelta.'],errors:['Encoger hombros.','Perder apoyo lumbar.']}
    ,{id:'machine_row',name:'Remo en máquina',muscle:'Espalda',equipment:'Máquina',level:'Principiante',pattern:'Tracción horizontal',alt:'Remo con apoyo de pecho',steps:['Apoya el pecho.','Tira de los codos hacia atrás.','Pausa y vuelve lento.'],errors:['Usar impulso.','Elevar los hombros.']}
    ,{id:'machine_shoulder',name:'Press de hombros en máquina',muscle:'Hombros',equipment:'Máquina',level:'Principiante',pattern:'Empuje vertical',alt:'Press militar sentado',steps:['Ajusta el asiento.','Empuja en plano escapular.','Baja hasta un rango cómodo.'],errors:['Arquear la espalda.','Bajar en exceso.']}
    ,{id:'cable_lateral',name:'Elevación lateral en polea',muscle:'Hombros',equipment:'Polea',level:'Intermedio',pattern:'Abducción',alt:'Elevaciones laterales',steps:['Colócate lateral a la polea.','Eleva el brazo hasta el hombro.','Vuelve lentamente.'],errors:['Inclinar el tronco.','Encoger trapecio.']}
    ,{id:'face_pull',name:'Face pull',muscle:'Hombros',equipment:'Polea',level:'Principiante',pattern:'Rotación externa y tracción',alt:'Pájaros en máquina',steps:['Tira de la cuerda hacia la cara.','Separa las manos.','Pausa con hombros bajos.'],errors:['Arquear la espalda.','Tirar hacia el pecho.']}
    ,{id:'cable_curl',name:'Curl en polea',muscle:'Bíceps',equipment:'Polea',level:'Principiante',pattern:'Flexión de codo',alt:'Curl martillo',steps:['Mantén codos fijos.','Flexiona sin balancear.','Extiende con control.'],errors:['Mover hombros.','Usar demasiado peso.']}
    ,{id:'rope_curl',name:'Curl con cuerda',muscle:'Bíceps',equipment:'Polea',level:'Principiante',pattern:'Flexión neutra',alt:'Curl martillo',steps:['Agarre neutro.','Flexiona manteniendo codos estables.','Separa ligeramente la cuerda arriba.'],errors:['Balancear el cuerpo.','Acortar el recorrido.']}
    ,{id:'pec_deck',name:'Pec deck',muscle:'Pecho',equipment:'Máquina',level:'Principiante',pattern:'Aducción horizontal',alt:'Aperturas en polea',steps:['Ajusta el asiento.','Cierra los brazos con control.','Regresa sin perder tensión.'],errors:['Llevar hombros hacia delante.','Golpear los topes.']}
    ,{id:'machine_hip_thrust',name:'Hip thrust en máquina',muscle:'Glúteos',equipment:'Máquina',level:'Principiante',pattern:'Extensión de cadera',alt:'Hip thrust',steps:['Ajusta la almohadilla.','Empuja desde los talones.','Pausa arriba.'],errors:['Hiperextender la espalda.','Separar los pies en exceso.']}
    ,{id:'hip_abduction',name:'Abducción de cadera en máquina',muscle:'Glúteos',equipment:'Máquina',level:'Principiante',pattern:'Abducción de cadera',alt:'Caminata lateral con banda',steps:['Apoya la espalda.','Abre las piernas de forma controlada.','Vuelve sin cerrar de golpe.'],errors:['Usar impulso.','Inclinar demasiado el tronco.']}
    ,{id:'hip_adduction',name:'Aducción de cadera en máquina',muscle:'Aductores',equipment:'Máquina',level:'Principiante',pattern:'Aducción de cadera',alt:'Copenhagen plank',steps:['Ajusta la apertura inicial.','Cierra las piernas con control.','Vuelve lentamente.'],errors:['Rebotar.','Forzar demasiado el rango.']}
    ,{id:'seated_calf',name:'Gemelo sentado',muscle:'Gemelos',equipment:'Máquina',level:'Principiante',pattern:'Flexión plantar',alt:'Gemelo de pie',steps:['Coloca la almohadilla sobre los muslos.','Baja el talón.','Sube y pausa.'],errors:['Rebotar.','Recorrido corto.']}
    ,{id:'legpress_calf',name:'Gemelo en prensa',muscle:'Gemelos',equipment:'Máquina',level:'Principiante',pattern:'Flexión plantar',alt:'Gemelo de pie',steps:['Apoya la punta de los pies.','Baja los talones con control.','Empuja hasta arriba.'],errors:['Doblar mucho las rodillas.','Perder apoyo.']}
    ,{id:'plank',name:'Plancha',muscle:'Core',equipment:'Peso corporal',level:'Principiante',pattern:'Anti-extensión',alt:'Dead bug',steps:['Alinea cabeza, tronco y pelvis.','Aprieta abdomen y glúteos.','Respira sin perder posición.'],errors:['Hundir la cadera.','Elevar demasiado la pelvis.']}
  ],

  recipes: [
    {id:'oats_yogurt',name:'Avena con yogur y frutos rojos',meal:'Desayuno',kcal:510,p:32,c:66,f:13,ingredients:['80 g avena','250 g yogur alto en proteína','100 g frutos rojos','15 g crema de cacahuete'],steps:['Mezcla avena y yogur.','Añade los frutos rojos.','Termina con la crema de cacahuete.','Deja reposar 5 minutos.']},
    {id:'egg_toast',name:'Tortilla de claras con pan',meal:'Desayuno',kcal:390,p:39,c:34,f:10,ingredients:['250 g claras','2 huevos','60 g pan integral','tomate'],steps:['Bate claras y huevos.','Cocina en sartén antiadherente.','Tuesta el pan.','Sirve con tomate.']},
    {id:'banana_shake',name:'Batido de avena y plátano',meal:'Desayuno',kcal:690,p:42,c:96,f:16,ingredients:['80 g avena','1 plátano','300 ml leche','30 g proteína','20 g crema de cacahuete'],steps:['Añade la leche a la batidora.','Incorpora el resto de ingredientes.','Bate 45-60 segundos.','Ajusta con hielo o agua.']},
    {id:'turkey_toast',name:'Tostadas de pavo y aguacate',meal:'Desayuno',kcal:470,p:31,c:46,f:17,ingredients:['100 g pan integral','100 g pavo','60 g aguacate','tomate'],steps:['Tuesta el pan.','Añade el pavo.','Machaca el aguacate.','Termina con tomate.']},
    {id:'chicken_rice',name:'Pollo con arroz y verduras',meal:'Comida',kcal:760,p:58,c:96,f:14,ingredients:['180 g pollo','120 g arroz en crudo','250 g verduras','10 g aceite'],steps:['Cuece el arroz.','Cocina el pollo troceado.','Saltea las verduras.','Mezcla y añade el aceite medido.']},
    {id:'beef_potato',name:'Ternera con patata al horno',meal:'Comida',kcal:670,p:48,c:72,f:20,ingredients:['170 g ternera magra','400 g patata','ensalada','10 g aceite'],steps:['Hornea la patata a 200 °C.','Cocina la ternera.','Prepara la ensalada.','Sirve con el aceite medido.']},
    {id:'pasta_tuna',name:'Pasta con atún y tomate',meal:'Comida',kcal:720,p:50,c:99,f:14,ingredients:['120 g pasta','160 g atún natural','150 g tomate triturado','10 g aceite'],steps:['Cuece la pasta al dente.','Escurre el atún.','Calienta el tomate.','Mezcla y añade el aceite.']},
    {id:'lentils_eggs',name:'Lentejas rápidas con huevo',meal:'Comida',kcal:610,p:38,c:75,f:18,ingredients:['300 g lentejas cocidas','2 huevos','verduras','5 g aceite'],steps:['Aclara las lentejas.','Saltea las verduras.','Añade las lentejas.','Sirve con los huevos cocidos o a la plancha.']},
    {id:'fish_potato',name:'Merluza con patata y ensalada',meal:'Comida',kcal:510,p:46,c:55,f:12,ingredients:['220 g merluza','300 g patata','ensalada','10 g aceite'],steps:['Cuece o asa la patata.','Cocina la merluza.','Prepara la ensalada.','Añade el aceite medido.']},
    {id:'fit_burger',name:'Hamburguesa fit con boniato',meal:'Comida',kcal:740,p:49,c:85,f:21,ingredients:['180 g carne magra','1 pan de hamburguesa','300 g boniato','verduras'],steps:['Hornea el boniato.','Forma y cocina la hamburguesa.','Calienta el pan.','Monta con verduras.']},
    {id:'yogurt_fruit',name:'Yogur proteico con fruta',meal:'Merienda',kcal:280,p:27,c:34,f:4,ingredients:['250 g yogur proteico','1 fruta','10 g miel'],steps:['Corta la fruta.','Mézclala con el yogur.','Añade miel.','Sirve frío.']},
    {id:'tuna_sandwich',name:'Sándwich de atún',meal:'Merienda',kcal:420,p:34,c:45,f:11,ingredients:['100 g pan integral','120 g atún','tomate','queso ligero'],steps:['Escurre el atún.','Monta el sándwich.','Añade tomate y queso.','Tuesta opcionalmente.']},
    {id:'quark_oats',name:'Queso fresco batido con avena',meal:'Merienda',kcal:480,p:38,c:59,f:10,ingredients:['300 g queso fresco batido','60 g avena','1 plátano'],steps:['Mezcla el queso y la avena.','Añade el plátano troceado.','Deja reposar 5 minutos.','Ajusta textura con leche o agua.']},
    {id:'protein_shake',name:'Batido de proteína y frutos secos',meal:'Merienda',kcal:430,p:36,c:35,f:17,ingredients:['30 g proteína','300 ml leche','20 g frutos secos','1 fruta'],steps:['Añade leche y proteína.','Incorpora la fruta.','Bate.','Toma los frutos secos aparte o tritúralos.']},
    {id:'chicken_veg',name:'Pollo salteado con verduras',meal:'Cena',kcal:440,p:52,c:28,f:14,ingredients:['200 g pollo','350 g verduras','10 g aceite'],steps:['Corta el pollo.','Saltéalo hasta cocinarlo.','Añade las verduras.','Incorpora el aceite medido al final.']},
    {id:'salmon_veg',name:'Salmón con verduras',meal:'Cena',kcal:560,p:43,c:25,f:31,ingredients:['180 g salmón','300 g verduras','150 g patata'],steps:['Hornea el salmón 12-15 minutos.','Cocina las verduras.','Cuece o asa la patata.','Sirve todo junto.']},
    {id:'egg_turkey',name:'Revuelto de huevos y pavo',meal:'Cena',kcal:410,p:43,c:18,f:18,ingredients:['3 huevos','120 g pavo','verduras'],steps:['Saltea las verduras.','Añade el pavo.','Incorpora los huevos batidos.','Cocina hasta cuajar.']},
    {id:'chicken_wraps',name:'Wraps de pollo',meal:'Cena',kcal:590,p:48,c:62,f:17,ingredients:['2 tortillas','170 g pollo','verduras','salsa de yogur'],steps:['Cocina el pollo.','Calienta las tortillas.','Reparte pollo y verduras.','Añade salsa y enrolla.']},
    {id:'tuna_chickpeas',name:'Ensalada de atún y garbanzos',meal:'Cena',kcal:540,p:42,c:55,f:17,ingredients:['160 g atún','200 g garbanzos','verduras','10 g aceite'],steps:['Aclara los garbanzos.','Escurre el atún.','Mezcla con verduras.','Añade aceite y condimentos.']},
    {id:'turkey_rice',name:'Pavo con arroz y calabacín',meal:'Cena',kcal:640,p:52,c:78,f:13,ingredients:['190 g pavo','100 g arroz','250 g calabacín','5 g aceite'],steps:['Cuece el arroz.','Cocina el pavo.','Saltea el calabacín.','Mezcla y añade el aceite.']}
  ]
};