(()=>{'use strict';
const $=id=>document.getElementById(id),R=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},W=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const LS={profile:'fitcoach_v5_profile',checkin:'fitcoach_v5_checkin',goal:'fitcoach_v5_goal'};
const safe=n=>Number.isFinite(+n)?+n:0,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function profile(){return R(LS.profile,{experience:'intermediate',goal:'recomp',days:4,minutes:50,equipment:'gym',sleep:7,steps:7000,meals:4,diet:'omnivore',allergies:'',injuries:'',priority:'balanced'})}
function workouts(){return R('workouts',[])}function metrics(){return R('metrics',[])}function targets(){return R('targets',{kcal:2200,protein:160,carbs:220,fat:70})}
function meals(){return R('meals',[])}function todayKey(){return window.FitCoachLocalDate?.localDateKey?.()||new Date().toISOString().slice(0,10)}
function weeklySessions(){let d=new Date();d.setDate(d.getDate()-6);d.setHours(0,0,0,0);return workouts().filter(x=>new Date(x.date)>=d).length}
function trend(){let a=metrics().filter(x=>safe(x.weight)>0).slice(-8);if(a.length<2)return 0;return +(safe(a.at(-1).weight)-safe(a[0].weight)).toFixed(2)}
function todayNutrition(){let t=meals().filter(x=>x.date===todayKey()),sum=k=>t.reduce((a,b)=>a+safe(b[k]),0),tg=targets();return{kcal:sum('kcal'),protein:sum('protein'),carbs:sum('carbs'),fat:sum('fat'),target:tg}}
function score(){let p=profile(),c=R(LS.checkin,{energy:7,soreness:3,stress:4,sleep:p.sleep||7}),s=weeklySessions(),sc=72+(safe(c.energy)-5)*4-(safe(c.soreness)-4)*2-(safe(c.stress)-5)*2+(safe(c.sleep)-7)*3;return clamp(Math.round(sc+s),35,100)}
function sciencePlan(){let p=profile(),ex=window.FITCOACH_DATA?.exercises||[],by=m=>ex.filter(x=>x.muscle===m),days=clamp(safe(p.days)||4,2,6),minutes=safe(p.minutes)||50;
 const splits={2:[['Pecho','Espalda','Cuádriceps','Isquios','Hombros'],['Cuádriceps','Isquios','Pecho','Espalda','Glúteos']],3:[['Pecho','Espalda','Hombros'],['Cuádriceps','Isquios','Glúteos'],['Pecho','Espalda','Bíceps','Tríceps']],4:[['Pecho','Espalda','Hombros'],['Cuádriceps','Isquios','Glúteos'],['Pecho','Espalda','Bíceps','Tríceps'],['Cuádriceps','Isquios','Glúteos','Hombros']],5:[['Pecho','Hombros','Tríceps'],['Espalda','Bíceps'],['Cuádriceps','Isquios','Glúteos'],['Pecho','Espalda','Hombros'],['Cuádriceps','Isquios','Bíceps','Tríceps']],6:[['Pecho','Hombros','Tríceps'],['Espalda','Bíceps'],['Cuádriceps','Isquios','Glúteos'],['Pecho','Hombros','Tríceps'],['Espalda','Bíceps'],['Cuádriceps','Isquios','Glúteos']]};
 const maxEx=minutes<=35?5:minutes<=50?6:7,used={};return splits[days].map((muscles,di)=>{let list=[];muscles.forEach(m=>{let pool=by(m);if(!pool.length)return;let idx=(used[m]||0)%pool.length;let e=pool[idx];used[m]=(used[m]||0)+1;let compound=!['Bíceps','Tríceps','Hombros','Gemelos','Core'].includes(m),sets=compound?3:2,reps=p.goal==='strength'&&compound?'4–6':compound?'6–10':'10–15';list.push({name:e.name,muscle:m,sets,reps,rir:'1–3',alt:e.alt||''})});return{name:['Día A','Día B','Día C','Día D','Día E','Día F'][di],items:list.slice(0,maxEx)}})}
function coachMessage(){let s=score(),tr=trend(),p=profile(),wn=weeklySessions(),t=todayNutrition(),msg=[];if(s<55)msg.push('Reduce hoy 1 serie por ejercicio y mantén 2–4 RIR.');else if(s<72)msg.push('Mantén cargas y evita forzar récords; prioriza técnica.');else msg.push('Preparación buena: progresa si completas el rango con 1–2 RIR.');if(wn<(safe(p.days)||4)-1)msg.push('La prioridad de la semana es completar sesiones antes que añadir técnicas avanzadas.');if(t.protein<t.target.protein*.65)msg.push(`Te faltan aprox. ${Math.max(0,Math.round(t.target.protein-t.protein))} g de proteína para el objetivo diario.`);if(tr>1.2&&p.goal==='fatloss')msg.push('El peso está subiendo; revisa adherencia y promedio calórico semanal.');if(tr<-1.5&&p.goal==='gain')msg.push('El peso está bajando; conviene aumentar energía de forma gradual.');return msg}
function renderHome(){let home=$('home');if(!home)return;let old=$('v5Dashboard');if(old)old.remove();let p=profile(),t=todayNutrition(),s=score(),plan=sciencePlan(),protPct=clamp(Math.round((t.protein/Math.max(1,t.target.protein))*100),0,140),kcalPct=clamp(Math.round((t.kcal/Math.max(1,t.target.kcal))*100),0,140);let box=document.createElement('div');box.id='v5Dashboard';box.className='v5-stack';box.innerHTML=`<div class="v5-hero"><div class="v5-eyebrow">FitCoach Intelligence</div><div class="v5-title">Tu plan cambia contigo.</div><div class="v5-sub">Entrenamiento, nutrición y recuperación en una sola decisión diaria.</div><div class="v5-grid" style="margin-top:16px"><div class="v5-metric"><b>${s}</b><span>Readiness</span></div><div class="v5-metric"><b>${weeklySessions()}/${p.days}</b><span>Sesiones 7 días</span></div><div class="v5-metric"><b>${Math.round(t.protein)}g</b><span>Proteína hoy</span></div><div class="v5-metric"><b>${trend()>0?'+':''}${trend()}kg</b><span>Tendencia peso</span></div></div></div><div class="v5-two"><div class="v5-section"><div class="v5-row"><div><h2>Coach de hoy</h2><p>Decisiones prácticas basadas en tus datos.</p></div><span class="v5-pill ${s<65?'warn':''}">${s>=80?'Listo para progresar':s>=65?'Normal':'Recuperación'}</span></div><div class="v5-list">${coachMessage().map((m,i)=>`<div class="v5-item"><span class="v5-num">${i+1}</span><div><strong>${m}</strong><small>Se ajusta con entrenamiento, ingesta, recuperación y tendencia.</small></div></div>`).join('')}</div></div><div class="v5-section"><h2>Nutrición hoy</h2><p>${Math.round(t.kcal)} / ${t.target.kcal} kcal</p><div class="v5-progress"><i style="width:${Math.min(100,kcalPct)}%"></i></div><div class="v5-divider"></div><p>${Math.round(t.protein)} / ${t.target.protein} g proteína</p><div class="v5-progress"><i style="width:${Math.min(100,protPct)}%"></i></div><div class="v5-chiprow"><span class="v5-chip">P ${t.target.protein}g</span><span class="v5-chip">C ${t.target.carbs||0}g</span><span class="v5-chip">G ${t.target.fat||0}g</span></div></div></div><div class="v5-section"><div class="v5-row"><div><h2>Plan científico sugerido</h2><p>${p.days} días · ${p.minutes} min · ${p.goal}</p></div><span class="v5-pill">~10+ series/músculo/sem</span></div><div class="v5-list">${plan.slice(0,2).map(d=>`<div class="v5-item"><span class="v5-num">${d.name.slice(-1)}</span><div><strong>${d.items.map(x=>x.muscle).join(' · ')}</strong><small>${d.items.slice(0,4).map(x=>`${x.name} ${x.sets}×${x.reps}`).join(' · ')}</small></div></div>`).join('')}</div><div class="v5-actions"><button data-v5go="training">Entrenar ahora</button><button class="secondary" data-v5go="nutrition">Comer según macros</button><button class="secondary" data-v5go="settings">Personalizar</button></div></div>`;home.prepend(box);box.querySelectorAll('[data-v5go]').forEach(b=>b.onclick=()=>document.querySelector(`nav [data-go="${b.dataset.v5go}"]`)?.click())}
function renderSettings(){let page=$('settings');if(!page||$('v5Profile'))return;let p=profile(),wrap=document.createElement('div');wrap.id='v5Profile';wrap.className='v5-section';wrap.style.marginBottom='16px';wrap.innerHTML=`<h2>Perfil inteligente</h2><p class="v5-help">Este perfil gobierna el entrenamiento, la nutrición y las recomendaciones.</p><div class="v5-form" style="margin-top:14px"><div class="row"><div><label>Objetivo</label><select id="v5Goal"><option value="recomp">Recomposición</option><option value="gain">Ganancia muscular</option><option value="fatloss">Pérdida de grasa</option><option value="strength">Fuerza</option></select></div><div><label>Experiencia</label><select id="v5Exp"><option value="beginner">Principiante</option><option value="intermediate">Intermedio</option><option value="advanced">Avanzado</option></select></div></div><div class="row"><div><label>Días/semana</label><input id="v5Days" type="number" min="2" max="6" value="${p.days}"></div><div><label>Minutos/sesión</label><input id="v5Minutes" type="number" min="25" max="120" value="${p.minutes}"></div></div><div class="row"><div><label>Sueño habitual</label><input id="v5Sleep" type="number" min="4" max="10" step=".5" value="${p.sleep}"></div><div><label>Pasos/día</label><input id="v5Steps" type="number" step="500" value="${p.steps}"></div></div><label>Lesiones / limitaciones</label><input id="v5Injuries" value="${String(p.injuries||'').replace(/"/g,'&quot;')}" placeholder="Ej. dolor de hombro, lesión de rodilla"><label>Preferencia alimentaria</label><select id="v5Diet"><option value="omnivore">Omnívora</option><option value="vegetarian">Vegetariana</option><option value="vegan">Vegana</option></select><button id="v5Save">Guardar y recalcular</button></div><div id="v5Saved" class="v5-banner" hidden style="margin-top:12px">Perfil actualizado. El coach ya usa estos datos.</div>`;page.insertBefore(wrap,page.children[1]||null);$('v5Goal').value=p.goal;$('v5Exp').value=p.experience;$('v5Diet').value=p.diet;$('v5Save').onclick=()=>{let n={...p,goal:$('v5Goal').value,experience:$('v5Exp').value,days:clamp(safe($('v5Days').value),2,6),minutes:clamp(safe($('v5Minutes').value),25,120),sleep:clamp(safe($('v5Sleep').value),4,10),steps:safe($('v5Steps').value),injuries:$('v5Injuries').value.trim(),diet:$('v5Diet').value};W(LS.profile,n);$('v5Saved').hidden=false;setTimeout(renderHome,50)}}
function renderCheckin(){let home=$('home');if(!home||$('v5Checkin'))return;let c=R(LS.checkin,{energy:7,soreness:3,stress:4,sleep:profile().sleep||7}),d=document.createElement('div');d.id='v5Checkin';d.className='v5-section';d.innerHTML=`<h2>Check-in de 20 segundos</h2><p>Ayuda a decidir si progresar, mantener o descargar.</p><div class="v5-form" style="margin-top:12px"><div class="row"><div><label>Energía 1–10</label><input id="v5Energy" type="number" min="1" max="10" value="${c.energy}"></div><div><label>Dolor muscular 1–10</label><input id="v5Soreness" type="number" min="1" max="10" value="${c.soreness}"></div></div><div class="row"><div><label>Estrés 1–10</label><input id="v5Stress" type="number" min="1" max="10" value="${c.stress}"></div><div><label>Horas de sueño</label><input id="v5SleepToday" type="number" min="3" max="12" step=".5" value="${c.sleep}"></div></div><button id="v5CheckSave">Actualizar coach</button></div>`;home.appendChild(d);$('v5CheckSave').onclick=()=>{W(LS.checkin,{energy:clamp(safe($('v5Energy').value),1,10),soreness:clamp(safe($('v5Soreness').value),1,10),stress:clamp(safe($('v5Stress').value),1,10),sleep:clamp(safe($('v5SleepToday').value),3,12)});renderHome();renderCheckin()}}
function boot(){renderSettings();renderHome();renderCheckin();document.querySelectorAll('nav [data-go]').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>{if(b.dataset.go==='home'){renderHome();renderCheckin()}if(b.dataset.go==='settings')renderSettings()},40)))}
window.addEventListener('load',()=>setTimeout(boot,120));
})();
