import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
const quality=require('../client-quality-v41.js');
const engine=require('../client-engine-v35.js');
quality.install(engine);

test('local plan dates use the civil day instead of UTC serialization',()=>{const d=new Date(2026,0,2,0,30,0);assert.equal(quality.localDateKey(d),'2026-01-02');});
test('allergy screening checks ingredient names, not only recipe title',()=>{const ingredients=[{id:'a',name:'Avena'},{id:'p',name:'Crema de cacahuete'},{id:'y',name:'Yogur'}];const recipes=[{id:'unsafe',name:'Bol energético',meal:'Desayuno/Merienda',ings:[['a',70],['p',20]]},{id:'safe',name:'Bol de yogur',meal:'Desayuno/Merienda',ings:[['a',60],['y',200]]}];assert.deepEqual(quality.filterAllergyUnsafeRecipes({allergies:'cacahuete'},recipes,ingredients).map(x=>x.id),['safe']);});
test('allergy matching is accent insensitive',()=>{assert.equal(quality.filterAllergyUnsafeRecipes({allergies:'cacahuete'},[{id:'x',name:'Receta',ings:[['p',20]]}],[{id:'p',name:'CACAHUÉTE tostado'}]).length,0);});
test('allergy screening rejects recipes with unresolved ingredients',()=>{const ingredients=[{id:'a',name:'Avena'}];const recipes=[{id:'unknown',name:'Bol',ings:[['a',50],['mystery',10]]},{id:'known',name:'Avena',ings:[['a',60]]}];assert.deepEqual(quality.filterAllergyUnsafeRecipes({allergies:'cacahuete'},recipes,ingredients).map(x=>x.id),['known']);assert.equal(quality.hasUnknownIngredients(recipes[0],Object.fromEntries(ingredients.map(x=>[x.id,x]))),true);});
test('dislikes are screened against hidden ingredient names',()=>{const ingredients=[{id:'t',name:'Tomate triturado'},{id:'r',name:'Arroz'}];const recipes=[{id:'hidden',name:'Bol mediterráneo',ings:[['r',80],['t',100]]},{id:'safe',name:'Arroz blanco',ings:[['r',90]]}];assert.deepEqual(quality.filterPreferenceUnsafeRecipes({dislikes:'tomate'},recipes,ingredients).map(x=>x.id),['safe']);});
test('menu validator rejects missing meals even without allergies',()=>{assert.throws(()=>quality.validateMenuStructure({days:[{meals:[{recipeId:'a'},{recipeId:'b'}]}]},{meals:4},1),/suficientes recetas/);});
test('menu validator rejects missing requested days',()=>{assert.throws(()=>quality.validateMenuStructure({days:[{meals:Array.from({length:4},(_,i)=>({recipeId:String(i)}))}]},{meals:4},2),/se solicitaron 2 días/);});
test('menu validator rejects non-finite or negative macro values',()=>{const meals=Array.from({length:4},(_,i)=>({recipeId:String(i),macros:{kcal:500,p:30,c:50,f:15}}));meals[2].macros.kcal=NaN;assert.throws(()=>quality.validateMenuStructure({days:[{meals}]},{meals:4},1),/datos nutricionales no válidos/);assert.equal(quality.validMacros({kcal:500,p:30,c:50,f:15}),true);assert.equal(quality.validMacros({kcal:-1,p:30,c:50,f:15}),false);});
test('training validator rejects missing or sparse sessions',()=>{assert.throws(()=>quality.validateTrainingStructure({routine:{Lunes:[{name:'A',sets:2,reps:'8-12'}]}},{days:2}),/incompleto|suficientes ejercicios/);assert.throws(()=>quality.validateTrainingStructure({routine:{Lunes:[{name:'A',sets:2,reps:'8-12'},{name:'B',sets:2,reps:'8-12'},{name:'C',sets:0,reps:'8-12'}],Martes:[{name:'D',sets:2,reps:'8-12'},{name:'E',sets:2,reps:'8-12'},{name:'F',sets:2,reps:'8-12'}]}},{days:2}),/suficientes ejercicios/);});
test('installed plan keeps duration and emits local-date keys',()=>{const muscles=['Pecho','Espalda','Cuádriceps','Isquios','Glúteos','Hombros','Bíceps','Tríceps','Core','Gemelos'];const library=muscles.map((muscle,i)=>({name:'Ejercicio '+i,muscle,equipment:'Máquina',alt:'Alternativa',pattern:'p'+i}));const plan=engine.buildTrainingPlan({days:4,weeks:8,equipment:['Máquina']},library);assert.match(plan.start,/^\d{4}-\d{2}-\d{2}$/);assert.match(plan.end,/^\d{4}-\d{2}-\d{2}$/);const [sy,sm,sd]=plan.start.split('-').map(Number),[ey,em,ed]=plan.end.split('-').map(Number);assert.equal(Math.round((new Date(ey,em-1,ed,12)-new Date(sy,sm-1,sd,12))/86400000),55);});
