const {test,expect}=require('@playwright/test');
const URL='http://127.0.0.1:4173/';
async function ready(page){await page.goto(URL,{waitUntil:'domcontentloaded'});const modal=page.locator('#fcIntakeModal');if(await modal.count()&&await modal.isVisible().catch(()=>false)){for(let i=0;i<3;i++)await page.locator('#fcNext').click();await page.locator('#fcGenerate').click();await page.waitForFunction(()=>localStorage.getItem('fitcoach_client_profile_v35')!==null);}await expect(page.locator('#home')).toBeVisible();}
async function nutrition(page){await ready(page);await page.locator('nav [data-go="nutrition"]').click();await expect(page.locator('#nutrition')).toBeVisible();}
function errors(page){const a=[];page.on('pageerror',e=>a.push(e.message));return a}
for(const [name,target] of [['Inicio','home'],['Plan','plan'],['Entrenar','training'],['Nutrición','nutrition'],['Progreso','progress'],['Ajustes','settings']])test(`usuario navega a ${name} sin romper estado`,async({page})=>{const e=errors(page);await ready(page);await page.locator(`nav [data-go="${target}"]`).click();await expect(page.locator(`#${target}`)).toBeVisible();expect(e).toEqual([])});
for(const width of [320,375,390,430])test(`usuario usa FitCoach a ${width}px sin scroll horizontal`,async({page})=>{await page.setViewportSize({width,height:760});await ready(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+2)).toBeTruthy()});
test('usuario cambia objetivo del plan',async({page})=>{await ready(page);await page.locator('nav [data-go="plan"]').click();await page.locator('#goal').selectOption('strength');await expect(page.locator('#goal')).toHaveValue('strength')});
test('usuario cambia días del plan',async({page})=>{await ready(page);await page.locator('nav [data-go="plan"]').click();await page.locator('#days').selectOption('3');await expect(page.locator('#days')).toHaveValue('3')});
test('usuario cambia duración del plan',async({page})=>{await ready(page);await page.locator('nav [data-go="plan"]').click();await page.locator('#minutes').selectOption('45');await expect(page.locator('#minutes')).toHaveValue('45')});
test('usuario introduce fecha de inicio',async({page})=>{await ready(page);await page.locator('nav [data-go="plan"]').click();await page.locator('#start').fill('2026-09-01');await expect(page.locator('#start')).toHaveValue('2026-09-01')});
test('nutrición nunca queda en blanco tras onboarding',async({page})=>{await nutrition(page);expect((await page.locator('#nutrition').innerText()).trim().length).toBeGreaterThan(20)});
test('nutrición ofrece una acción visible',async({page})=>{await nutrition(page);expect(await page.locator('#nutrition button:visible').count()).toBeGreaterThan(0)});
test('nutrición ofrece datos o controles interactivos',async({page})=>{await nutrition(page);const count=await page.locator('#nutrition input:visible,#nutrition select:visible,#nutrition button:visible').count();expect(count).toBeGreaterThan(0)});
test('nutrición sigue operativa al recargar',async({page})=>{await nutrition(page);await page.reload({waitUntil:'domcontentloaded'});await page.locator('nav [data-go="nutrition"]').click();await expect(page.locator('#nutrition')).toBeVisible()});
test('nutrición cabe en iPhone pequeño',async({page})=>{await page.setViewportSize({width:320,height:700});await nutrition(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+2)).toBeTruthy()});
test('usuario guarda un nombre de perfil',async({page})=>{await ready(page);await page.locator('nav [data-go="settings"]').click();await page.locator('#profileName').fill('Usuario QA');page.once('dialog',d=>d.accept());await page.locator('#saveProfile').click();await expect(page.locator('#profileName')).toHaveValue('Usuario QA')});
test('usuario ve controles táctiles suficientemente grandes',async({page})=>{await ready(page);const small=await page.locator('nav button:visible').evaluateAll(ns=>ns.filter(n=>{const r=n.getBoundingClientRect();return r.height<44}).length);expect(small).toBe(0)});
test('usuario puede usar teclado para enfocar navegación',async({page})=>{await ready(page);await page.keyboard.press('Tab');expect(await page.evaluate(()=>document.activeElement!==document.body)).toBeTruthy()});
test('usuario con reducir movimiento mantiene la app operativa',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await ready(page);await expect(page.locator('#home')).toBeVisible()});
test('usuario vuelve Inicio tras visitar varias áreas',async({page})=>{await ready(page);for(const t of ['training','nutrition','progress','home'])await page.locator(`nav [data-go="${t}"]`).click();await expect(page.locator('#home')).toBeVisible()});
test('usuario recarga y conserva el perfil unificado',async({page})=>{await ready(page);const before=await page.evaluate(()=>localStorage.getItem('fitcoach_client_profile_v35'));expect(before).toBeTruthy();await page.reload({waitUntil:'domcontentloaded'});expect(await page.evaluate(()=>localStorage.getItem('fitcoach_client_profile_v35'))).toBe(before)});
test('usuario no recibe errores de página al recorrer navegación completa',async({page})=>{const e=errors(page);await ready(page);for(const t of ['plan','training','nutrition','progress','settings','home'])await page.locator(`nav [data-go="${t}"]`).click();expect(e).toEqual([])});
